version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.local
      target: debug
    env_file: .env
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
  db:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=RWLocal
      - POSTGRES_PASSWORD=docker
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - pgdata-rwperformance:/var/lib/postgresql/data
  redis:
    image: 'redis:latest'
    ports:
      - 6379:6379
    command: '--requirepass docker'
    volumes:
      - redis-data:/data
  redisinsight:
    image: 'redislabs/redisinsight:latest'
    ports:
      - 8001:8001
volumes:
  pgdata-rwperformance:
  redis-data:
